version: '3.8'

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - USE_OMDB_FALLBACK=true
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - ./media:/media
    ports:
      - "8096:8096"
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - media-network

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=UTC
      - USE_OMDB_FALLBACK=true
    ports:
      - "5055:5055"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - ./jellyseerr:/app/config
    restart: unless-stopped
    networks:
      - media-network

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - ./sonarr:/config
      - ./media/tv:/tv
      - ./downloads:/downloads
    ports:
      - "8989:8989"
    restart: unless-stopped
    networks:
      - media-network
      - vpn-network

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - ./radarr:/config
      - ./media/movies:/movies
      - ./downloads:/downloads
    ports:
      - "7878:7878"
    restart: unless-stopped
    networks:
      - media-network
      - vpn-network

VPN_SERVICE_PLACEHOLDER

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - ./prowlarr:/config
    ports:
      - "9696:9696"
    restart: unless-stopped
    networks:
      - media-network
      - vpn-network
    depends_on:
      - vpn-service

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - WEBUI_PORT=8085
    volumes:
      - ./qbittorrent:/config
      - ./downloads:/downloads
    restart: unless-stopped
    network_mode: "service:vpn-service"
    depends_on:
      - vpn-service

  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - ./bazarr:/config
      - ./media/movies:/movies
      - ./media/tv:/tv
    ports:
      - "6767:6767"
    restart: unless-stopped
    networks:
      - media-network

networks:
  media-network:
    driver: bridge
  vpn-network:
    driver: bridge
