version: '3.8'

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    environment:
      - USE_OMDB_FALLBACK=true
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - ./media:/media
    ports:
      - "8096:8096"
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - media-network

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - USE_OMDB_FALLBACK=true
      - LOG_LEVEL=debug
      - TZ=UTC
    ports:
      - "5055:5055"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - ./jellyseerr:/app/config
    restart: unless-stopped
    networks:
      - media-network

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - USE_OMDB_FALLBACK=true
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - ./sonarr:/config
      - ./media/tv:/tv
      - ./downloads:/downloads
    ports:
      - "8989:8989"
    restart: unless-stopped
    networks:
      - media-network
      - vpn-network

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - USE_OMDB_FALLBACK=true
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - ./radarr:/config
      - ./media/movies:/movies
      - ./downloads:/downloads
    ports:
      - "7878:7878"
    restart: unless-stopped
    networks:
      - media-network
      - vpn-network

  mullvad-vpn:
    image: qmcgaw/gluetun:latest
    container_name: mullvad-vpn
    cap_add:
      - NET_ADMIN
    environment:
      - USE_OMDB_FALLBACK=true
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=openvpn
      - OPENVPN_USER=YOUR_MULLVAD_ACCOUNT_NUMBER_HERE
      - OPENVPN_PASSWORD=m
      - SERVER_COUNTRIES=Netherlands
      - UPDATER_PERIOD=24h
    ports:
      - "8085:8085"  # qBittorrent
      - "6881:6881"  # qBittorrent torrent port
      - "6881:6881/udp"
    restart: unless-stopped
    networks:
      - vpn-network

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - USE_OMDB_FALLBACK=true
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - ./prowlarr:/config
    ports:
      - "9696:9696"
    restart: unless-stopped
    networks:
      - media-network
      - vpn-network
    depends_on:
      - mullvad-vpn

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - USE_OMDB_FALLBACK=true
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - WEBUI_PORT=8085
    volumes:
      - ./qbittorrent:/config
      - ./downloads:/downloads
    restart: unless-stopped
    network_mode: "service:mullvad-vpn"
    depends_on:
      - mullvad-vpn

  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - USE_OMDB_FALLBACK=true
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - ./bazarr:/config
      - ./media/movies:/movies
      - ./media/tv:/tv
    ports:
      - "6767:6767"
    restart: unless-stopped
    networks:
      - media-network

networks:
  media-network:
    driver: bridge
  vpn-network:
    driver: bridge
